import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Terms of Service",
  description:
    "The terms and conditions governing your use of the ClawCove platform.",
};

export default function TermsOfServicePage() {
  return (
    <main className="mx-auto max-w-3xl px-6 py-16 sm:py-24">
      <Link
        href="/"
        className="mb-10 inline-flex items-center gap-1.5 text-sm text-foreground-muted transition-colors hover:text-foreground"
      >
        <span aria-hidden="true">&larr;</span> Back to Home
      </Link>

      <header className="mb-10">
        <h1 className="text-4xl font-bold tracking-tight">
          Terms of Service
        </h1>
        <p className="mt-3 text-sm text-foreground-muted">
          Last updated: March 10, 2026
        </p>
      </header>

      <div className="prose prose-lg max-w-none prose-headings:tracking-tight prose-a:text-primary-500 prose-a:transition-colors hover:prose-a:text-primary-600">
        <p>
          These Terms of Service (&quot;Terms&quot;) govern your access to and
          use of the ClawCove platform operated by ClawCove (&quot;we,&quot;
          &quot;us,&quot; or &quot;our&quot;). By using ClawCove, you agree to
          be bound by these Terms.
        </p>

        <h2>1. The Service</h2>
        <p>
          ClawCove provides a managed, always-on personal AI assistant hosted in
          the cloud. Your AI agent is powered by{" "}
          <a
            href="https://openclaw.ai/"
            target="_blank"
            rel="noopener noreferrer"
          >
            OpenClaw
          </a>{" "}
          and can perform tasks such as drafting emails, managing schedules, and
          automating workflows on your behalf.
        </p>

        <h2>2. Eligibility</h2>
        <p>
          You must be at least 13 years old to use ClawCove. By creating an
          account, you represent that you meet this requirement and that the
          information you provide is accurate and complete.
        </p>

        <h2>3. Your Account</h2>
        <p>
          You are responsible for maintaining the security of your account
          credentials. You agree to notify us immediately of any unauthorized
          access. We are not liable for losses arising from unauthorized use of
          your account.
        </p>

        <h2>4. Acceptable Use</h2>
        <p>You agree not to use ClawCove to:</p>
        <ul>
          <li>Violate any applicable law or regulation.</li>
          <li>
            Generate, distribute, or store content that is illegal, harmful,
            threatening, abusive, or otherwise objectionable.
          </li>
          <li>
            Attempt to gain unauthorized access to our systems or other
            users&apos; accounts.
          </li>
          <li>
            Interfere with or disrupt the service or the servers and networks
            connected to it.
          </li>
          <li>
            Use the service to send unsolicited messages or engage in automated
            abuse.
          </li>
          <li>
            Reverse engineer, decompile, or attempt to extract the source code
            of the service.
          </li>
        </ul>

        <h2>5. Your Content</h2>
        <p>
          You retain ownership of the content you create through ClawCove. By
          using the service, you grant us a limited license to process your
          content solely to operate and improve the service. We do not claim
          ownership of your data or the outputs generated by your AI agent.
        </p>

        <h2>6. AI-Generated Output</h2>
        <p>
          Your AI agent produces outputs based on the instructions you provide.
          While we strive for accuracy, AI-generated content may contain errors
          or inaccuracies. You are responsible for reviewing and verifying any
          output before relying on it, especially for consequential decisions.
        </p>

        <h2>7. Availability &amp; Uptime</h2>
        <p>
          We aim to keep ClawCove available around the clock, but we do not
          guarantee uninterrupted service. Scheduled maintenance, infrastructure
          issues, or circumstances beyond our control may cause temporary
          downtime. We will make reasonable efforts to notify you of planned
          outages in advance.
        </p>

        <h2>8. Payment &amp; Billing</h2>
        <p>
          Certain features of ClawCove may require a paid subscription. Pricing,
          billing cycles, and payment terms will be presented at the time of
          purchase. All fees are non-refundable unless otherwise stated or
          required by law.
        </p>

        <h2>9. Termination</h2>
        <p>
          You may close your account at any time. We may suspend or terminate
          your access if you violate these Terms or if required by law. Upon
          termination, your right to use the service ceases immediately. We will
          make your data available for export for 30 days after account closure.
        </p>

        <h2>10. Limitation of Liability</h2>
        <p>
          To the maximum extent permitted by law, ClawCove and its officers,
          employees, and partners shall not be liable for any indirect,
          incidental, special, consequential, or punitive damages arising from
          your use of the service. Our total liability shall not exceed the
          amount you paid us in the 12 months preceding the claim.
        </p>

        <h2>11. Disclaimer of Warranties</h2>
        <p>
          ClawCove is provided &quot;as is&quot; and &quot;as available&quot;
          without warranties of any kind, whether express or implied, including
          but not limited to implied warranties of merchantability, fitness for a
          particular purpose, and non-infringement.
        </p>

        <h2>12. Changes to These Terms</h2>
        <p>
          We may revise these Terms from time to time. Material changes will be
          communicated via email or a prominent notice on our website at least 30
          days before taking effect. Your continued use of ClawCove after changes
          take effect constitutes acceptance of the revised Terms.
        </p>

        <h2>13. Governing Law</h2>
        <p>
          These Terms are governed by and construed in accordance with applicable
          law, without regard to conflict of law principles.
        </p>

        <h2>14. Contact</h2>
        <p>
          Questions about these Terms? Reach out at{" "}
          <a href="mailto:legal@clawcove.com">legal@clawcove.com</a>.
        </p>
      </div>
    </main>
  );
}
